variables:
  APP_NAME: "react-sample"
  NAMESPACE: "arbeon-chatops"
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com/utils
  ECR_TOKEN: secret-password

  SERVICE_PORT: 3000

stages:
  - build

docker-image:
  stage: docker-image
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  services:
    - docker:20.10.16-dind
  script:
    - if [ "$CI_COMMIT_TAG" ]; then IMAGE_TAG=${CI_COMMIT_TAG}; else IMAGE_TAG=${CI_COMMIT_SHORT_SHA}; fi
    - echo ${IMAGE_TAG}
    - docker build -t ${APP_NAME} .
    - docker tag ${APP_NAME} ${ECR_REPO_URL}/${APP_NAME}:${IMAGE_TAG}
    - docker push ${ECR_REPO_URL}/${APP_NAME}:${IMAGE_TAG}
  tags:
    - dev