variables:
  APP_NAME: "react"
  NAMESPACE: "arbeon-chatops"
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_TOKEN: secret-password

  SERVICE_PORT: 80
  SERVICE_TYPE: "NodePort"

  CERT_DNS: "react.arbeon.com"
  INGRESS_HOST: "react.arbeon.com"
  IMAGE_TAG: "b16d19f2"
  AWS_REGION: "ap-northeast-2"
  ENV: "production"
  EKS_CLUSTER_NAME: "arbeon-production-cls"

   # INGRESS
  ALB_NAME: "grpc-alb"
  ALB_SCHEME: "internet-facing"
  # "*.arbeon.com" cert-arn AS
  ALB_CERT_ARN: "arn:aws:acm:ap-northeast-2:873799242473:certificate/9f247e95-7e34-4921-b07d-90fe76924a44"
  # "*.arbeon.com" cert-arn US
  # ALB_CERT_ARN: "arn:aws:acm:us-west-1:873799242473:certificate/855e930e-2050-47a4-89d9-ad96275ed71b"
  # "*.staging-merge.com" cert-arn
  # ALB_CERT_ARN: "arn:aws:acm:us-west-1:873799242473:certificate/a8698851-7dd3-4c4d-afe4-83f2d60e4031"

stages:
  - deploy

deploy:
  stage: deploy
  image: ${ECR_REPO_URL}/utils/aws-helm:1.0.0
  script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - kubectl get nodes
    # values ymal 파일에 변수 주입
    - envsubst < helm/values.yaml.template > ./helm/values.yaml
    - helm upgrade ${APP_NAME} ./helm --install --values=./helm/values.yaml --create-namespace --namespace=${NAMESPACE}
    - cat ./helm/values.yaml
  tags:
    - aws-runner
  environment:
    name: ${ENV}
    url: https://${INGRESS_HOST}
    on_stop: stop-helm

stop-helm:
  stage: deploy
  image: ${ECR_REPO_URL}/utils/aws-helm:1.0.0
  script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - helm uninstall ${APP_NAME} --namespace=${NAMESPACE}
  tags:
    - aws-runner
  except:
    - tags
  environment:
    name: ${ENV}
    action: stop
  when: manual

