variables:
  APP_NAME: "react"
  NAMESPACE: "arbeon-chatops"
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_TOKEN: secret-password

  SERVICE_PORT: 80
  SERVICE_TYPE: "NodePort"

  CERT_DNS: "*.arbeon.com"
  INGRESS_HOST: "react.arbeon.com"
  IMAGE_TAG: "b16d19f2"
  AWS_REGION: "us-west-1"
  ENV: "production-us"
  EKS_CLUSTER_NAME: "us-arbeon-production-cls"

stages:
  - deploy

deploy:
  stage: deploy
  image: ${ECR_REPO_URL}/utils/aws-helm:1.0.0
  script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - kubectl get nodes
    # values ymal 파일에 변수 주입
    - envsubst < helm-eks/values.yaml.template > ./helm-eks/values.yaml
    - helm upgrade ${APP_NAME} ./helm-eks --install --values=./helm-eks/values.yaml --create-namespace --namespace=${NAMESPACE}
  tags:
  environment:
    name: ${ENV}
    url: https://${INGRESS_HOST}
    on_stop: stop-helm-eks

stop-helm-eks:
  stage: deploy
  image: ${ECR_REPO_URL}/utils/aws-helm:1.0.0
  script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - helm uninstall ${APP_NAME} --namespace=${NAMESPACE}
  tags:
    - aws-runner
  except:
    - tags
  environment:
    name: ${ENV}
    action: stop
  when: manual

