variables:
  APP_NAME: "react"
  NAMESPACE: "arbeon-chatops"
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_TOKEN: secret-password

  SERVICE_PORT: 80
  SERVICE_TYPE: "ClusterIP"

  CERT_DNS: "*.arbeon.com"
  INGRESS_HOST: "dev-react.arbeon.com"
  KUBE_CONFIG: ${DEV_KUBE_CONFIG}
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}


stages:
  - semantic-versioning
  - test


semantic-versioning:
  stage: semantic-versioning
  image: ${ECR_REPO_URL}/utils/aws-helm:1.0.0
  variables:
    GIT_STRATEGY: clone
  script:
    - git fetch --prune-tags
    - npx semantic-release --no-ci
  after_script: # 다음 스테이지에 git 설치 안하기 위해서 버전을 파일로 저장
    - echo "after versioning"
    - latest_version=$(git describe --tags --abbrev=0)
    - echo $latest_version
    - echo "export latest_version=$latest_version" > ./version.txt
  artifacts:
    paths:
      - ./version.txt
  only:
    - develop
  except:
    - tags
  tags:
    - dev

test-workflow:
  image: docker:latest
  stage: test
  tags:
    - dev
  except:
    - tags
  script:
    - echo ${CI_PIPELINE_SOURCE}
    - echo ${CI_COMMIT_BRANCH}
    - echo ${CI_COMMIT_REF_NAME}
    - echo ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  
  

