include:
  - project: 'ETC/devops/cicd-templates'
    file: 'semantic-versioning.yml'

variables:
  APP_NAME: "react"
  NAMESPACE: "arbeon-chatops"
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_TOKEN: secret-password

  SERVICE_PORT: 80
  SERVICE_TYPE: "ClusterIP"

  CERT_DNS: "*.arbeon.com"
  INGRESS_HOST: "dev-react.arbeon.com"
  KUBE_CONFIG: ${DEV_KUBE_CONFIG}
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /feature/
      variables:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
    - when: always

stages:
  - semantic-versioning
  - test


test-workflow:
  image: docker:latest
  stage: test
  tags:
    - dev
  script:
    - echo ${CI_PIPELINE_SOURCE}
    - echo ${CI_COMMIT_BRANCH}
    - echo ${CI_COMMIT_REF_NAME}
    - echo ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  
  

